### ISSUE TITLE
New Kali release

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#10201]
New Kali release 1.6.52 so users get the memory performance improvements

**Comment by andresriancho** [comment]
Sent email to @sbrun asking her to package the new dependencies. Once that's done I can test the new .deb in https://github.com/andresriancho/w3af-kali

**Comment by andresriancho** [comment]
@sbrun answered that she'll package the required dependencies next week(s)

**Comment by andresriancho** [comment]
Also added PIPDependency('psutil', 'psutil', '2.2.1') , but that should be part of Kali already (need to check)

**Comment by andresriancho** [comment]
http://pkg.kali.org/pkg/python-psutil
kali:0.5.1-1
kali-dev:2.1.1-1

**Comment by sbrun** [comment]
Hi,
these packages are in kali-proposed-updates (maybe you need to wait a few hours to see them):
- python-psutil (version 2.1.1-1~kali1)
- python-lxml (version 3.4.0-1~kali1)
- python-ruamel.ordereddict (version 0.4.8-0kali1)
- python-pybloomfiltermmap (version 0.3.14-0kali2): it replaces python-bloomfiltermmap which is in kali. The package has been introduced in debian with an other name. I kept the debian package name.

**Comment by andresriancho** [comment]
You rock. Going to work on this on the next days

**Comment by andresriancho** [comment]
@sbrun I've pushed the latest changes to needed to build the w3af.deb package for Kali to https://github.com/andresriancho/w3af-kali , those changes were tested and were found to be working without any issues in an environment which has kali-pu in `sources.list`.

Please note the changes to https://github.com/andresriancho/w3af-kali/blob/master/debian/control , where I specified new requirements and for some packages which were already required I specified the version.

Please merge my `w3af-kali` repo into your `git://git.kali.org/packages/w3af.git` and start the process of building a new w3af.deb to push to kali-pu

I'm not 100% sure how this works, but keep in mind that if w3af.deb version 1.6.54 is pushed to the main kali repos without the following dependencies (which are also in kali-pu now) things will break!
 * http://pkg.kali.org/pkg/python-psutil
 * http://pkg.kali.org/pkg/lxml
 * http://pkg.kali.org/pkg/ruamel.ordereddict
 * http://pkg.kali.org/pkg/pybloomfiltermmap

Let me know if there is anything else I need to do in order to have 1.6.54 in kali main repos, thanks!

**Comment by sbrun** [comment]
The new version 1.6.54-0kali1 is now in kali-rolling and in kali-proposed-updates.
We update the debian/rules (to simplify it) so it would be great if you could test the package to be sure there is no regression. Thanks

**Comment by andresriancho** [comment]
@sbrun thanks for merging into kali repos. Here some notes on my tests:

 * Merged your changes into https://github.com/andresriancho/w3af-kali
 * Build w3af.deb
 * Run automated tests against the newly build deb and **they failed**, it seems that the new build dependency you guys added to debian/control breaks something? `w3af-console depends on python:any (>= 2.7.1-0ubuntu2).` (see [this build](https://circleci.com/gh/andresriancho/w3af-kali-ci/34) , sign-up is free using your github account)

Something that I don't understand is why that dependency says "ubuntu"? Isn't Kali a Debian based distribution? Maybe it's my test environment... did you guys test the new w3af.deb (minor smoke tests to make sure it installs and starts after the changes to the package metadata)?

**Comment by sbrun** [comment]
I think that your test environment is not correct. It seems it's using ubuntu:
```sudo docker run -v /home/ubuntu/w3af-kali-ci/w3af-kali/docker:/w3af/ -i -t --name w3af-kali --rm andresriancho/w3af-kali 1.6.54```
The .deb built in kali depends on python (>= 2.6.6-7~). 
I had installed the packages and started the program  without problem in kali and kali-rolling.

**Comment by andresriancho** [comment]
w3af needs python >=2.7 to run, could you please specify that in the control files?

I'll change my test environment and try again, it might take a while, starting to work on something else today.

**Comment by andresriancho** [comment]
I haven't tested it, but it might be that the ubuntu reference seen in the tests comes from building the .deb in ubuntu

**Comment by andresriancho** [comment]
Hah, yes, this is inside the .deb file: `Depends: python:any (>= 2.7.1-0ubuntu2)`, it seems that the `${python:Depends}` from the control file is replaced (at build time) with the ubuntu specific package name

**Comment by sbrun** [comment]
I uploaded a new version 1.6.54-0kali2 with the minimal required version 
of python 2.7 in debian/control.

**Comment by andresriancho** [comment]
## TODO for me:
 - [ ] Download and test the w3af.deb built by Sophie
 - [ ] Merge Sophie's changes into w3af-kali
 - [ ] Check if there is any way to stop the variable replacing issue in ubuntu

**Comment by LocutusOfBorg** [comment]
@kali folks,

I packaged some dependencies in Debian
https://packages.qa.debian.org/p/python-darts.lib.utils.lru.html
python-esmre
python-phply
sqlmap
python-3to2 (dependency of something above IIRC)
and something more will follow.

The goal is to package 1.6.54+ in Debian, feel free to drop some of your packages in flavour of the Debian ones :)

**Comment by andresriancho** [comment]
@LocutusOfBorg that sounds really good :+1: I believe that the guys will need more details, such as:
 * Which python module versions were packaged?
 * Which distribution "branch" (stable|unstable|experimental) are they in?

And a question from my side: How does pulling work from Kali to Debian? How often does Kali pull packages from the Debian repo to make them available in Kali?

**Comment by LocutusOfBorg** [comment]
We always upload on unstable (new stuff), so the branch is unstable/testing.

Kali is based on Debian, I guess from Jessie or Stretch, so they might want to dget the dsc files and upload on their server.
(note: I do not know much about kali, but pulling stuff from Debian should be easier than packaging it separately)
the versions are available on the PTS and are the latest upstream versions.
darts.* 0.5-2
esmre: 0.3.1-2
phply: 0.9.1-1
sqlmap: 0.9.150525-1 (I already have a new snapshot on git)
3to2: 1.0-1

You can have a good picture on my ddpo page:
https://qa.debian.org/developer.php?login=costamagnagianfranco@yahoo.it
(Hint, I gave you my mail :p )

**Comment by andresriancho** [comment]
@sbrun tested manually on kali, all working!
