### ISSUE TITLE
Websockets stuff from nixwizard

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#10395]
## Description
A long time ago @nixwizard send me an email with the things he coded for websocket security analysis, this is (mostly) his words and code, that need to be merged into the current develop branch

extended_urrlib.py, modification is not needed. I've attached it just to show you how I implemented bauth flag in send_mutant() method. But eventually, I've managed to make plugin without it, so I'dont know if we will need this in the future.

Most of the testing I did with websocketstest.com. But  it will work only if you patch https://github.com/andresriancho/w3af/blob/cb3b5dfee1d1a311c9e4f7576a1971fb08cc6369/w3af/core/data/url/HTTPRequest.py#L84 to something like this:

```python
self.headers[key[0].upper()+key[1:]] = val
```

Remember that terrible bug I've found!

Other tests were done using `mod_pywebsockets` (which luckily supports basic authorization). Lots of the time was spent on trying to mock cfg.get and cfg.save, and it actually worked, but eventually I understood that we don't need to mock cfg object at all.

As you can see in test_cswsh.py, I've managed to get set basic auth information via new `FastHTTPBasicAuthHandler` with preconfigured password manager object `HTTPPasswordMgrWithDefaultRealm` which contains required basic auth credentials in it.

The weak part of this plugin is links detection, because by now it only detects static links, and huge number of sites will generate it dynamically with js. So we need to think about implementing some mechanism to implement it dynamically, otherwise this plugin would be useless for lots of websites.

The files are all in [this gist](https://gist.github.com/andresriancho/045a84747e13d5adb6d0)

## Tasks
 - [x] Review all existing code
 - [x] Find the original task associated with the code
 - [x] Create feature branch, merge code into it
 - [x] Fix the code and tests
   - [x] Note the `TODO: I'm not sure what happens here. What if I'm in a case where the`
 - [x] Change tests to run against httpretty
 - [x] Test data save/read from grep plugin / to audit plugin
 - [x] Save new vulnerability titles to vulns.py
 - [x] Merge code into develop
 - [ ] Send email to @nixwizard thanking him for the code
 - [ ] Ask @cschneider4711 to review the plugin code

**Comment by andresriancho** [comment]
Should work on this today, after finishing with #4681

**Comment by andresriancho** [comment]
This plugin will find the `ws://` links:
https://github.com/andresriancho/w3af/blob/develop/w3af/plugins/grep/websockets_links.py

This plugin identifies the vulnerabilities:
https://github.com/andresriancho/w3af/blob/develop/w3af/plugins/audit/websocket_hijacking.py

This is the test for the audit plugin:
https://github.com/andresriancho/w3af/blob/develop/w3af/plugins/tests/audit/test_websocket_hijacking.py

@nixwizard thanks for your code!
@cschneider4711 Could you please review the code? The most important part is the `audit/websocket_hijacking.py` where checks are made!

**Comment by andresriancho** [comment]
@nixwizard @cschneider4711 feel free to comment on this issue, I'll reopen it if needed
