### ISSUE TITLE
Complete libmproxy implementation

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#10429]
## Preparation tasks
 - [x] Read https://github.com/andresriancho/w3af/pull/4165 in detail
 - [x] Read https://github.com/andresriancho/w3af/issues/1269
 - [x] Read https://github.com/andresriancho/w3af/issues/183
 - [x] Create a detailed TODO list with all the pending tasks
 - [x] Let @m0sth8 know I'll be taking over his PR
 - [x] Close https://github.com/andresriancho/w3af/issues/1269
 - [x] Close https://github.com/andresriancho/w3af/issues/183
 - [x] Move all the code from PR https://github.com/andresriancho/w3af/pull/4165 to a feature branch

## TODO
 - [x] Create feature branch: feature/libmitmproxy
 - [x] [Close PR](https://github.com/andresriancho/w3af/pull/4165/files), referencing this issue
 - [x] Read mitmproxy documentation on how to extend it ([controller.Master](http://mitmproxy.org/doc/scripting/libmproxy.html) and all that)
    * `Proxy(Process)` is the thread running the ProxyServer (maybe I can remove this proxy process?)
    * `ProxyServer(server.ProxyServer)` listens on the socket
    * `Master(controller.Master)` receives the request/response and forwards it to the handler
    * `Handler.handle_request` receives the request, does something specific and forwards it to the server
 - [x] Add mitmproxy==0.12.1 to requirements
 - [x] Add mitmproxy==0.12.1 to kali packaging TODO list
 - [x] `tornado` is used by mitmproxy, does that work well with threads? Asked [here](https://groups.google.com/forum/#!topic/mitmproxy/jI6wOtZTbz8)
 - [x] mitmproxy has A LOT of dependencies, see comment below, do they play nice with w3af's dependencies? **No**
   - [x] pyOpenSSL>=0.15.1 (from netlib<0.13,>=0.12->mitmproxy) conflicts with pyOpenSSL==0.13.1. Need to bump the openssl version to at least 0.15.1 (how does this affect Kali?). Question asked [here](https://groups.google.com/forum/#!topic/mitmproxy/iVJppB6TNnY)
 - [x] Manually merge PR into feature branch
  - [x] Merge unittests
  - [x] Write more unittests for the libmproxy code/integration
  - [x] Merge code
 - [x] Make sure LocalProxy (localproxy.py) works and is properly unittested
  - [x] Create test that queues more than one request for multiple URL paths, make sure the order of the responses is the expected one. This test is failing, but using the interception proxy manually works, I suspect it's the test.
 - [x] Remove the awful hacks I was doing before
 - [x] Set better names for:
   - [x] w3afLocalProxyHandler
   - [x] w3afProxyHandler
 - [x] Understand how mitmproxy handles SSL certificates:
   - [x] Does it create a new certificate for each https domain visited? Yes
   - [x] Does it sign those certificates with a CA we can specify? Yes, use [Using a custom certificate authority](http://mitmproxy.org/doc/certinstall.html) to generate our w3af CA!
   - [x] Does it create the CA certificate on each run? No, see above
   - [x] If required, create a new CA certificate with w3af.org name to be used by mitmproxy library
 - [x] Enable `test_xurllib_proxy.py:TestExtendedUrllibProxy.test_https_via_proxy` test
 - [x] Enable `test_sqlmap_wrapper.py:TestSQLMapWrapper.test_verify_vulnerability_ssl`
 - [x] Remove the `self.fix_content_length` option from all local proxy subclasses
 - [x] Create documentation on how to handle SSL certificates with spiderman at [this doc page](https://github.com/andresriancho/w3af/blob/master/doc/sphinx/complex-web-apps.rst)
 - [x] Manually test GUI's localproxy
  - [x] Verify that the certificates are generated by our CA
 - [x] Find all imports/uses of *ProxyHandler, proxy, LocalProxy, etc.
 - [x] Make sure that there is no code referencing w3afLocalProxyHandler, w3afProxyHandler, etc.
 - [x] `nosetests ./w3af/core/data/url/tests/test_xurllib_proxy.py` is failing
  * But `./w3af/core/controllers/daemons/proxy/tests/test_proxy.py` sends SSL requests and works
  * The difference seems to be that in one I use extended urllib (which fails)
  * Fixed!
 - [x] Merge into develop
 - [x] Verify that the links from gui tools and advanced application point to the right document for configuring the CA
 - [x] Thank @m0sth8 for his PR

**Comment by andresriancho** [comment]
mitmproxy dependencies:

Requirement already satisfied (use --upgrade to upgrade): mitmproxy in /home/pedro/pch/virtual-envs/w3af/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pyperclip>=1.5.8 in /home/pedro/pch/virtual-envs/w3af/lib/python2.7/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>0.1.2 in /home/pedro/pch/virtual-envs/w3af/lib/python2.7/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): tornado>=4.0.2 in /home/pedro/pch/virtual-envs/w3af/lib/python2.7/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): lxml>=3.3.6 in /home/pedro/pch/virtual-envs/w3af/lib/python2.7/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): netlib<0.13,>=0.12 in /home/pedro/pch/virtual-envs/w3af/lib/python2.7/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): blinker>=1.3 in /home/pedro/pch/virtual-envs/w3af/lib/python2.7/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): Pillow>=2.3.0 in /home/pedro/pch/virtual-envs/w3af/lib/python2.7/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): urwid>=1.3 in /home/pedro/pch/virtual-envs/w3af/lib/python2.7/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): configargparse>=0.9.3 in /home/pedro/pch/virtual-envs/w3af/lib/python2.7/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname in /home/pedro/pch/virtual-envs/w3af/lib/python2.7/site-packages (from tornado>=4.0.2->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): certifi in /home/pedro/pch/virtual-envs/w3af/lib/python2.7/site-packages (from tornado>=4.0.2->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): cffi in /home/pedro/pch/virtual-envs/w3af/lib/python2.7/site-packages (from netlib<0.13,>=0.12->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): pyOpenSSL>=0.15.1 in /home/pedro/pch/virtual-envs/w3af/lib/python2.7/site-packages (from netlib<0.13,>=0.12->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): cryptography>=0.9 in /home/pedro/pch/virtual-envs/w3af/lib/python2.7/site-packages (from netlib<0.13,>=0.12->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): passlib>=1.6.2 in /home/pedro/pch/virtual-envs/w3af/lib/python2.7/site-packages (from netlib<0.13,>=0.12->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): hpack>=1.0.1 in /home/pedro/pch/virtual-envs/w3af/lib/python2.7/site-packages (from netlib<0.13,>=0.12->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /home/pedro/pch/virtual-envs/w3af/lib/python2.7/site-packages (from cffi->netlib<0.13,>=0.12->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in /home/pedro/pch/virtual-envs/w3af/lib/python2.7/site-packages (from pyOpenSSL>=0.15.1->netlib<0.13,>=0.12->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): idna in /home/pedro/pch/virtual-envs/w3af/lib/python2.7/site-packages (from cryptography>=0.9->netlib<0.13,>=0.12->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /home/pedro/pch/virtual-envs/w3af/lib/python2.7/site-packages (from cryptography>=0.9->netlib<0.13,>=0.12->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): enum34 in /home/pedro/pch/virtual-envs/w3af/lib/python2.7/site-packages (from cryptography>=0.9->netlib<0.13,>=0.12->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): ipaddress in /home/pedro/pch/virtual-envs/w3af/lib/python2.7/site-packages (from cryptography>=0.9->netlib<0.13,>=0.12->mitmproxy)
