### ISSUE TITLE
Please check for installed sqlmap

### ISSUE THREAD

**Issue by LocutusOfBorg** [andresriancho/w3af#10538]
As in the title, since I'm trying to package it for Debian, and I already have sqlmap packaged
(you can see the list of files installed there)
```https://packages.debian.org/sid/all/sqlmap/filelist```
basically I copy the sources in /usr/share/sqlmap
```https://sources.debian.net/src/sqlmap/0.9.150525-1/debian/install/ ```

is it possible to check for the installed version?

Second question:
Debian do not want a python-clamd package, since it seems to be a badly maintainer fork of pyclamd.

Is it possible to patch the code to use the latter instead of the former?
the RFP/ITP was here
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=725170

and the package I would like to use  is here
https://packages.qa.debian.org/p/pyclamd.html

I didn't go through all the dependencies required, but they are (I guess) the last two big issues in having the last version in Debian/Backbox.

(the last pip version is coming in Debian in the next days, but hopefully it won't be needed, since the dependencies can't be "pip installed" here :) )

However it is a nice tool to see how much stuff I need to package :)

thanks!

**Comment by andresriancho** [comment]
Thanks for reporting this issue, I've been trying to get w3af updated in Debian for a long time and finally someone is starting to do so :+1: 

If you've got any questions that believe are better suited for an email, feel free to send me questions/requirements to andres.riancho@gmail.com

## TODO
 * Check if sqlmap is in PATH and use that instead of the embedded sqlmap
   - [ ] What happens if the user has an old sqlmap installed, which doesn't support a flag/option provided by w3af?
 - [ ] Analyze the possibility of changing to https://packages.qa.debian.org/p/pyclamd.html , since it does seem that pyclamd has better support than the other (currently in use) package.
   - [ ] What happens with Kali packages? Is https://packages.qa.debian.org/p/pyclamd.html also available in Kali?

**Comment by LocutusOfBorg** [comment]
*"What happens if the user has an old sqlmap installed, which doesn't support a flag/option provided by w3af?"

I'm packaging each month the last snapshot available on github (the master branch) and it is mostly bug fixes.
I will update sqlmap prior to each w3af update, so they will work well together.

(kali users needs to pick them both, to be sure they fits well too).
You should update it prior to each release.

Do you like that approach? :)

* https://packages.qa.debian.org/p/pyclamd.html

it is available since old old stable (so it was packaged before 2008)
o-o-stable 0.1.1-2 
oldstable  0.2.2-1 
stable   0.3.9-2 
testing    0.3.9-2 
unstable  0.3.9-2 

Kali seems to fetch from Debian (I would guess testing or stable), so there shouldn't be any problem there (they actually are the same version, and moreover almost the last upstream one).
I opened a bug there for having the last version in unstable

**Comment by LocutusOfBorg** [comment]
The debian bug is http://bugs.debian.org/789388

**Comment by andresriancho** [comment]
> Do you like that approach? :)

I don't usually trust humans. You can get bored and stop maintaining the sqlmap package and keep maintaining w3af, or the other way around, or simply stop doing all and someone else does it in a different way.

I believe the thing that w3af needs to do here is:
 * Check if there is a sqlmap installed and in PATH
 * If it's there then check it's version (maybe sqlmap --version? not sure how to retrieve that) and compare it against the versions which w3af knows how to communicate with
 * If sqlmap is not in PATH, or the version is unknown then use the sqlmap bundled with w3af

Another option is to use the sqlmap REST API to communicate (but that one might also change)

So, your goal is to package w3af inside Debian without [this](https://github.com/andresriancho/w3af/tree/master/w3af/plugins/attack/db/sqlmap) directory, correct? Is that mandatory to package it or just a good thing to do? (which I agree would save disk space for users which have both sqlmap and w3af installed)

**Comment by LocutusOfBorg** [comment]
Yes, I would strip that directory from the tarball.
It isn't *mandatory* to do such things in Debian (e.g. it is forbidden in Fedora), but it is the right thing to do, and nobody usually package the same library twice, because you know, other than the disk space it is problematic for CVEs and various other issues...

So I really would like to strip the directory from the tarball, yes :+1: 

The approach I thought might be:
* Check if there is an sqlmap directory embedded available
* If the directory is not there try to use the system installed sqlmap

checking the version is not possible right now, because sqlmap returns
```
sqlmap --version
1.0-dev-nongit-20150621
```
and that date is "today", not the date I did the snapshot (didn't check why the code returns that, I do not think it is the installation date, but I installed it some minutes ago)

**Comment by andresriancho** [comment]
Ok, all understood then. How quickly do you want me to move on these changes?

**Comment by LocutusOfBorg** [comment]
there is no rush, I'm still waiting for the new pip to hit debian unstable :)

**Comment by andresriancho** [comment]
Ok, leaving this in the queue while I finish other tasks. Anyways it might get done before the end of the week

**Comment by LocutusOfBorg** [comment]
there are still some missing dependencies in Debian I guess, but with the old pip I can't know which dependencies are missing, and I would like to see this fixed prior to continue the work (and pip is the major blocker at this point, since the import of the pip module used fails with 1.5.6)

**Comment by andresriancho** [comment]
Find me on IRC and we'll talk, `__apr__`  #w3af channel, freenode

**Comment by andresriancho** [comment]
Ok, going to work on this now, if @LocutusOfBorg has any objections / additions to what needs to be done: Talk now :mega:

**Comment by LocutusOfBorg** [comment]
I didn't change my opinion, I guess the priorities are:
use sqlmap from Debian
use pyclamd.

I'm pinging right now for pip, in the meanwhile python-guess-language got accepted yesterday
https://packages.qa.debian.org/p/python-guess-language.html

it was waiting for python-3to2 (it was python3 only until yesterday).

For the missing dependencies I'll take care as soon as I have time and I sort out what is missing in Debian

**Comment by andresriancho** [comment]
Awesome!

**Comment by andresriancho** [comment]
pyclamd migration: Done.

Lunch and then the sqlmap stuff

**Comment by LocutusOfBorg** [comment]
Debian updates:

```
pygithub
pybloomfiltermmap
pdfminer
ndg-httpsclient
msgpack-python
python-psutil
```
needs update to the latest upstream version (I'll wait a month or so and then ping again the maintainers)
(actually pygithub has an RC bug, but we can I guess remove the python3 package)

```
stopit
halberd
vulndb
ruamel.ordereddict
```
are missing, I'll package them

pip needs to be updated, with no ETA (but I guess it will be updated after the VAC

**Comment by andresriancho** [comment]
@LocutusOfBorg in https://github.com/andresriancho/w3af/commit/bd6759a3f76f35b6cdfad52fe2379273cbda6c84 you can see the changes for sqlmap. The decision was to use the sqlmap that's in PATH only if the embedded one is not present (which will be the case for debian since you're removing that directory).

Also, I'm assuming that `sqlmap` is a valid command and that it will be in PATH.

Finally, the whole thing fails if the embedded sqlmap is not present and there is no `sqlmap` command in PATH.

**Comment by andresriancho** [comment]
stopit is not required anymore see https://github.com/andresriancho/w3af/blob/master/w3af/core/controllers/dependency_check/requirements.py for an updated requirement list.

**Comment by andresriancho** [comment]
My TODOs related to this task are all done, but I'm not closing this issue since more things might come up and it's also a nice way of communicating with @LocutusOfBorg

**Comment by LocutusOfBorg** [comment]
Another question: why do we need ndg-httpsclient?

**Comment by LocutusOfBorg** [comment]
updated the missing Debian dependencies list with the removed dependency, and took this list instead
https://github.com/andresriancho/w3af/blob/develop/w3af/core/controllers/dependency_check/requirements.py

since AFAICS this is the development branch list, I do not need right now the stable one :)

**Comment by andresriancho** [comment]
@LocutusOfBorg ndg-httpsclient is related to SSL / TLS / SNI

**Comment by LocutusOfBorg** [comment]
@andresriancho I do not see in the code where it is actually used :)

**Comment by LocutusOfBorg** [comment]
I did some grep in the source code for httpclient, httpsclient, ndg, but I couldn't find anything useful..
and git log doesn't help either

**Comment by LocutusOfBorg** [comment]
@andresriancho ping about ndg-httpsclient code :)

**Comment by andresriancho** [comment]
Detailed research on the ndg-httpsclient issue shows that:
 * w3af's code doesn't reference it directly
 * The results of running `find . -name '*.py' | xargs grep 'ndg'` in the virtualenv are:
```
./lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py:* ndg-httpsclient (tested with 0.3.2)
./lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py:    pip install pyopenssl ndg-httpsclient pyasn1
./lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py:    from ndg.httpsclient.ssl_peer_verification import SUBJ_ALT_NAME_SUPPORT
./lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py:    from ndg.httpsclient.subj_alt_name import SubjectAltName as BaseSubjectAltName
./lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py:### Note: This is a slightly bug-fixed version of same from ndg-httpsclient.
./lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py:### Note: This is a slightly bug-fixed version of same from ndg-httpsclient.
./lib/python2.7/site-packages/ndg/httpsclient/__init__.py:"""ndg_httpsclient - PyOpenSSL utility to make a httplib-like interface suitable
./lib/python2.7/site-packages/ndg/httpsclient/urllib2_build_opener.py:from ndg.httpsclient.https import HTTPSContextHandler
./lib/python2.7/site-packages/ndg/httpsclient/ssl_peer_verification.py:"""ndg_httpsclient - module containing SSL peer verification class.
./lib/python2.7/site-packages/ndg/httpsclient/ssl_peer_verification.py:    from ndg.httpsclient.subj_alt_name import SubjectAltName
./lib/python2.7/site-packages/ndg/httpsclient/ssl_context_util.py:"""ndg_httpsclient SSL Context utilities module containing convenience routines
./lib/python2.7/site-packages/ndg/httpsclient/ssl_context_util.py:from ndg.httpsclient.ssl_peer_verification import ServerSSLCertVerification
./lib/python2.7/site-packages/ndg/httpsclient/https.py:"""ndg_httpsclient HTTPS module containing PyOpenSSL implementation of
./lib/python2.7/site-packages/ndg/httpsclient/https.py:from ndg.httpsclient.ssl_socket import SSLSocket
./lib/python2.7/site-packages/ndg/httpsclient/test/__init__.py:"""Unit tests package for ndg_httpsclient
./lib/python2.7/site-packages/ndg/httpsclient/test/test_urllib2.py:"""unit tests module for ndg.httpsclient.urllib2_build_opener module
./lib/python2.7/site-packages/ndg/httpsclient/test/test_urllib2.py:from ndg.httpsclient.test import Constants
./lib/python2.7/site-packages/ndg/httpsclient/test/test_urllib2.py:from ndg.httpsclient.urllib2_build_opener import build_opener
./lib/python2.7/site-packages/ndg/httpsclient/test/test_utils.py:"""unit tests module for ndg.httpsclient.utils module
./lib/python2.7/site-packages/ndg/httpsclient/test/test_utils.py:from ndg.httpsclient.test import Constants
./lib/python2.7/site-packages/ndg/httpsclient/test/test_utils.py:from ndg.httpsclient.utils import (Configuration, fetch_from_url, open_url,
./lib/python2.7/site-packages/ndg/httpsclient/test/test_utils.py:    '''Test ndg.httpsclient.utils module'''
./lib/python2.7/site-packages/ndg/httpsclient/test/test_https.py:"""unit tests module for ndg.httpsclient.https.HTTPSconnection class
./lib/python2.7/site-packages/ndg/httpsclient/test/test_https.py:from ndg.httpsclient.test import Constants
./lib/python2.7/site-packages/ndg/httpsclient/test/test_https.py:from ndg.httpsclient.https import HTTPSConnection
./lib/python2.7/site-packages/ndg/httpsclient/test/test_https.py:from ndg.httpsclient.ssl_peer_verification import ServerSSLCertVerification
./lib/python2.7/site-packages/ndg/httpsclient/test/test_https.py:    '''Test ndg HTTPS client HTTPSConnection class'''
./lib/python2.7/site-packages/ndg/httpsclient/utils.py:from ndg.httpsclient.urllib2_build_opener import build_opener
./lib/python2.7/site-packages/ndg/httpsclient/utils.py:from ndg.httpsclient.https import HTTPSContextHandler
./lib/python2.7/site-packages/ndg/httpsclient/utils.py:from ndg.httpsclient import ssl_context_util
./lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py:* ndg-httpsclient (tested with 0.3.2)
./lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py:    pip install pyopenssl ndg-httpsclient pyasn1
./lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py:    from ndg.httpsclient.ssl_peer_verification import SUBJ_ALT_NAME_SUPPORT
./lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py:    from ndg.httpsclient.subj_alt_name import SubjectAltName as BaseSubjectAltName
./lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py:### Note: This is a slightly bug-fixed version of same from ndg-httpsclient.
./lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py:### Note: This is a slightly bug-fixed version of same from ndg-httpsclient.
./lib/python2.7/site-packages/docutils/writers/latex2e/__init__.py:  \endgroup%
./lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py:* ndg-httpsclient (tested with 0.3.2)
./lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py:from ndg.httpsclient.ssl_peer_verification import SUBJ_ALT_NAME_SUPPORT
./lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py:from ndg.httpsclient.subj_alt_name import SubjectAltName
./lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py:### Note: This is a slightly bug-fixed version of same from ndg-httpsclient.
```
Which seem to show that (after checking that we don't use requests nor urllib3) w3af doesn't require ndg-httpsclient (not even a dependency of one of our dependencies)
 * Found a potential reason to believe that we need it:
https://github.com/andresriancho/w3af/blob/develop/w3af/core/data/url/openssl/subj_alt_name.py

## Solution
 * Check which version of ndg-httpsclient the file `subj_alt_name` came from
 * Diff that file with the latest from `ndg-httpsclient`
 * Remove `w3af/core/data/url/openssl/subj_alt_name.py` and change the imports to the ndg module

**Comment by LocutusOfBorg** [comment]
I don't see in the file history that version
https://github.com/cedadev/ndg_httpsclient/commits/master/ndg/httpsclient/subj_alt_name.py

evidences shows that file got introduced on 02/02/2015, but on the upstream repository nothing is similar to that...

**Comment by andresriancho** [comment]
Solution applied, will merge into develop once tests pass, but it all looks good.

Now w3af has one less file, and actually uses the dependency it asked people to install :+1: 

Thanks!

**Comment by LocutusOfBorg** [comment]
update:

Debian packages that needs an update
```
pygithub
pybloomfiltermmap
pdfminer
msgpack-python
python-psutil
```
packages in new queue
ruanel.ordereddict and vulndb are in new queue
and I became maintainer of ndg :)
and halberd has been accepted

**Comment by LocutusOfBorg** [comment]
BTW thanks for your fix!

**Comment by andresriancho** [comment]
PS: [This](https://github.com/andresriancho/w3af/issues/12058) might affect your packaging efforts

**Comment by LocutusOfBorg** [comment]
I have already a tracked down bug for it :)
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=789782

**Comment by LocutusOfBorg** [comment]
mitmproxy is on Debian.

All the dependencies should be there now.

**Comment by andresriancho** [comment]
Awesome! What now? May I test the latest w3af package in a docker running debian?

**Comment by LocutusOfBorg** [comment]
I could upload in experimental, but I would like to do it after a tagged release.

You can clone the git from there
http://anonscm.debian.org/cgit/collab-maint/w3af.git

and git-buildpackage it

**Comment by LocutusOfBorg** [comment]
do you plan a new release soon? now we can go for unstable I guess :)

**Comment by andresriancho** [comment]
I'm having a ton of projects at the moment, [new release and some other bug fixes](https://github.com/andresriancho/w3af/milestones/1.7%20-%20REST%20API) will have to wait at least 1 month.

Sorry about that

**Comment by LocutusOfBorg** [comment]
Hi, no problem, it is just sad that we won't probably be able to make it into the next ubuntu LTS
https://wiki.ubuntu.com/XenialXerus/ReleaseSchedule
the freeze is on 18 feb (and I have to upload in Debian at least one day before)

let me know if that deadline is possible, otherwise I'll try to make it go in backports probably or in the next ubuntu
(I don't want to break the freeze with such large changes!)

**Comment by LocutusOfBorg** [comment]
the new package (we uploaded a git snapshot) is now in unstable, but won't migrate because of https://github.com/andresriancho/w3af/issues/13876
