### ISSUE TITLE
ValueError('Invalid vulnerability DB id: %s' % vulndb_id)

### ISSUE THREAD

**Issue by 1d3df9903ad** [andresriancho/w3af#10612]
## TODO
 - [x] Is the `./lib/python2.7/site-packages/vulndb/db/73-information-leak-stack-trace.json` file found in Kali? **Yes**
 - [x] Does a `DBVuln.is_valid_id(vulndb_id)` call from python shell in Kali raise an exception? **No, everything works as expected**
 - [x] Is this a bug with the `debian/control` and old versions of the vulndb deb package being run with new versions of w3af? **It's not this issue**
 - [ ] More research is required? This vulnerability has appeared a couple of times but I'm unsure if it's my fault or the user's

## Version Information
```
  Python version: 2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]
  GTK version: 2.24.10
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.51
    Distribution: Kali Linux
    Author: Andres Riancho and the w3af team.
```
## Traceback
```pytb
A "ValueError" exception was found while running grep.error_pages on
 "Method: GET | http://domain/server-status". The exception was: 
"Invalid vulnerability DB id: 73" at info.py:set_vulndb_id():277.The full traceback is:
  File "/usr/share/w3af/w3af/core/controllers/core_helpers/consumers/grep.py", line 76, in run
    plugin.grep_wrapper(request, response)
  File "/usr/share/w3af/w3af/core/controllers/plugins/grep_plugin.py", line 55, in grep_wrapper
    self.grep(fuzzable_request, response)
  File "/usr/share/w3af/w3af/plugins/grep/error_pages.py", line 158, in grep
    self.find_version_numbers(request, response)
  File "/usr/share/w3af/w3af/plugins/grep/error_pages.py", line 192, in find_version_numbers
    response.id, self.get_name())
  File "/usr/share/w3af/w3af/core/data/kb/info.py", line 71, in __init__
    self.set_name(name)
  File "/usr/share/w3af/w3af/core/data/kb/info.py", line 210, in set_name
    self.set_vulndb_id(VULNS.get(name, None))
  File "/usr/share/w3af/w3af/core/data/kb/info.py", line 277, in set_vulndb_id
    raise ValueError('Invalid vulnerability DB id: %s' % vulndb_id)

```

**Comment by andresriancho** [comment]
http://git.kali.org/gitweb/?p=packages/python-vulndb.git;a=tree;f=vulndb/db;h=92716572da8c24f1a406ec5faf9b3212efab9902;hb=HEAD
