### ISSUE TITLE
Disk is filled when scans take a lot of time

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#15961]
## User story
As a user I want to scan really large sites (a lot of URLs, forms, images). In order to scan those sites I have to set `max_discovery_time` to a large value such as 1440 minutes (24 hours). While scanning that site I notice that the `main.db_traces` directory uses a lot of disk space and my disk is filled.

## Technical details
 * `main.db_traces` contains HTTP requests and responses for the HTTP cache and database
 * The HTTP cache and database are used for:
   * Returning HTTP responses from the cache
   * Generating reports: When an output plugin runs it accesses the HTTP request/response information associated with a vulnerability from the cache

## Proposed solution
 * Convince the user to run shorter scans :wink: 
 * Buy larger disks :dollar: 
 * Remove cache entries to reduce disk usage

## Auto cache cleanup
 * Cache entries associated with a vulnerability should **never be removed from disk**. w3af needs to keep track of this information in order to prevent them from being removed.
 * The cache should use at most 500mb of disk
 * In order for the cache to be useful, it has to maintain the cached entries for a while. Different cache eviction strategies could be implemented: only keep N items in the cache; or only use up to N% of disk space; or remove entries which haven't been read in N minutes (LRU). I believe that LRU which removes items that haven't been used recently when the 500mb disk usage is exceeded is the best.

Fragmentation: If the scan has many HTTP responses which have vulnerabilities, lets say 499mb worth of them, then the "real cache" will be only 1mb in size. This cache fragmentation is bad but I believe can't be avoided. Maybe debug log this situation?

Warn the user when a scan starts and there is less than 500mb + 10% of disk space left.

Let advanced users change the amount of disk the scan can use.

## Code sections to review
All areas of the code where `HistoryItem()` is called should be reviewed.

 - [ ] The worse thing that can happen is that we remove a cache entry that is afterwards needed by an output plugin. I need to make sure that all output plugins know how to handle this scenario.
 - [ ] Some plugins, such as [csp](https://github.com/andresriancho/w3af/blob/master/w3af/plugins/grep/csp.py#L84) and [click_jacking](https://github.com/andresriancho/w3af/blob/master/w3af/plugins/grep/click_jacking.py#L62) use the fact that everything that goes into the cache will stay in the cache for ever. They will do some processing at `end()` (which is called at the end of the scan) and write a vulnerability to the KB referencing those request IDs, which were not associated with a vulnerability before (cache would remove them) and are now. This will bring serious issues.
 - [ ] REST API `traffic.py`
 - [ ] GUI code which calls `HistoryItem()` to show the HTTP request and response in the GUI

## Severity
While this issue *is important* since it affects advanced users, it seems to be only reproducible on some sites and scan configurations.

## Effort
I initially though:

> This issue requires 6h of work to be resolved and tested.

## Task List
 - [ ] Think: Should we have request and response DB in one place, and cache in another? Should they be completely different things? Right now they are the same and it is complicating things a little bit. If we remove something from the DB we remove it from the cache: **not good**.
 - [ ] What if we save the request and response in the knowledge base, together with the vuln/info object? That way each time something enters the KB we'll know that the request and response associated with it will be available afterwards. This would require a minor change in the `Info` class that will "expand" the object with the request and response data, based on the ids. Then this "fat" instance is serialized and after that the request and response from the `Info` is used: the DB is never queried again.
 - [ ] history.py `_load_from_file()` retries several times before giving up. This doesn't sound like a good idea for situations in which the file containing the request and response does not exist on disk. A lot of delays will be added.

## Won't Fix
Sadly, after a mode detailed analysis I found that it would be **very expensive** to fix this issue since: *plugins were developed knowing that ALL HTTP REQUESTS and RESPONSES are in the database*. Breaking that statement would have huge impact on how all plugins work. 

The workaround (which worked pretty well) was to compress traffic https://github.com/andresriancho/w3af/issues/15972
