### ISSUE TITLE
Rebase dwsync_xml plugin to work with the latest framework

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#1827]
This is a nice plugin to have:
 * https://github.com/andresriancho/w3af/tree/dwsync_xml

It has been sitting there for a long time, and it would be awesome to have it in our codebase.

Original author is @tvelazquez 

## Tasks
 - [x] Create a new branch `feature/dwsync_xml`
 - [x] Update the plugin to use the latest framework features
 - [x] Write unittest for the plugin 
 - [x] Merge into develop
 - [x] Remove branch dwsync_xml
