### ISSUE TITLE
Rebase ds_store plugin to work with the latest framework

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#1828]
This is a nice plugin to have:
- https://github.com/andresriancho/w3af/tree/ds_store
- https://github.com/andresriancho/w3af/commit/f0c1b5b8a524d295aea661a91550c237f2160dc6

It has been sitting there for a long time, and it would be awesome to have it in our codebase.

Original author is @tvelazquez
## Tasks
- [x] Split parser and plugin in two different files
- [x] Update the plugin to use the latest framework features
- [x] Write unittest for the plugin

**Comment by andresriancho** [comment]
Do not merge this into develop yet, I'm working on a new Kali release and this branch adds a new dependency which is not yet in Kali.

I need to complete #10821 and then merge into develop

https://github.com/andresriancho/w3af-kali/issues/11

**Comment by andresriancho** [comment]
Build https://circleci.com/gh/andresriancho/w3af/2455

**Comment by andresriancho** [comment]
When done remove these branches:
 * https://github.com/andresriancho/w3af/tree/ds_store
 * https://circleci.com/gh/andresriancho/w3af/tree/feature%2Fds_store

**Comment by andresriancho** [comment]
https://github.com/andresriancho/w3af/commit/715787b43dbe447e8421c03c55f0771dd545928b
