### ISSUE TITLE
GET translates data kwarg into querystring

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#4681]
## Description
GET translates data kwarg into querystring, this makes it impossible to send a GET request which contains a post-data.

## History
 * w3af has behaved like this since the beginning
 * This is a known bug, and an ugly one
 * The change seems simple:
    * https://github.com/andresriancho/w3af/commit/505764f87b7ebd910746a0a854de4e499f2a8d39
    * https://github.com/andresriancho/w3af/commit/3d2222268e088cc7db0930fb2e3f28041c7622dc
 * Those changes trigger strange errors in the build:
   * https://circleci.com/gh/andresriancho/w3af/1029

## Priority
At the beginning this task was tagged as high priority, but I've changed it to low priority since it doesn't affect the users, just developers who want to send a GET with post-data (and those can wait), and plugins which try to do the same thing (which I'm not aware of any)

## Task
 - [x] Apply those changes again, but this time in a feature branch
 - [x] Change the xurllib (similar changes to the one I [reverted](https://github.com/andresriancho/w3af/commit/e79bc49f6e8de6861d69df837252104c5b59c438))
 - [x] Unittests
    - [x] Send a GET request with post-data to the server
    - [x] Send a GET request with post-data AND a QS to the server
 - [x] Identify all calls to `GET` which send `data` and expect it to be a QS.
 - [x] Identify all calls to xurllib which use `getattr`
 - [x] Change all pieces of code that used the old argument
 - [x] Review all the build errors and fix them
 - [x] Merge into develop

**Comment by andresriancho** [comment]
Initial test run was better than expected: https://circleci.com/gh/andresriancho/w3af/1978

**Comment by andresriancho** [comment]
This build should succeed :+1: 

https://circleci.com/gh/andresriancho/w3af/1980
