### ISSUE TITLE
Experiment with Disk queues in ThreadPool to reduce memory usage

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#4685]
## Idea
Setting the 500 size limit to the `self._inqueue` seems to lower the memory usage considerably:

```python
class Pool(ThreadPool):

    def __init__(self, processes=None, initializer=None, initargs=(),
                 worker_names=None):
        self.Process = partial(DaemonProcess, name=worker_names)
        ThreadPool.__init__(self, processes, initializer, initargs)
    
    def _setup_queues(self):
        self._inqueue = Queue.Queue(500)
        self._outqueue = Queue.Queue()
```
**IMPORTANT**: It might be better to limit the size of the `_taskqueue` instead of the `_inqueue`

## Potential issue
In order to be sure that this 500 limit doesn't dead-lock me, I need to add a test case to my suite that has an HTML with 500 * 2 URLs to crawl. It should be an endless site, with links and lorem ipsum. Another way to avoid dead-locks would be to use disk queues.

Please note that dead-locks could be an issue, and using "disk queues" is a solution:
 * https://pypi.python.org/pypi/queuelib
 * http://code.activestate.com/recipes/501154-persistent-queue/

## Serialization
Assumption: All objects sent to the queue are serializable.
Sure?

## Tasks
Both of these libs look good, I would just have to run tests for them:
 - [x] Run performance test without any change and [save to wiki](https://github.com/andresriancho/w3af/wiki/Performance-history)
 - [ ] Run performance test with queuelib
 - [ ] Run performance test with recipe
 - [ ] Compare results

For all tasks use https://github.com/andresriancho/collector

## References
w3af consumes lots of memory when running against huge site #1954
