### ISSUE TITLE
Experiment with Disk queues in consumers to reduce memory usage

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#4686]
## Idea
Setting a size limit to the input and output queues of consumers might reduce the memory usage.

## Potential issue
Dead-locks could appear if we limit the size of the queues. Using disk queues is a solution. Some libraries which I've found for this are:
 * https://pypi.python.org/pypi/queuelib
 * http://code.activestate.com/recipes/501154-persistent-queue/

## Serialization
Assumption: All objects sent to the queue are serializable.
Sure?

## Tasks
Both of these libs look good, I would just have to run tests for them:
 - [x] Run performance test without any change, [save baseline to wiki](https://github.com/andresriancho/w3af/wiki/Performance-history)
 - [ ] Run performance test with queuelib
 - [ ] Run performance test with recipe
 - [ ] Compare results

For all tasks use https://github.com/andresriancho/collector

Compare.

## References
 * w3af consumes lots of memory when running against huge site #1954
 * Experiment with Disk queues in ThreadPool to reduce memory usage #4685
