### ISSUE TITLE
Fix SQLLite database related issues

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#4937]
## Story
As usual, when we fix some things, other parts of the code get more stressed and start failing. In this case I'm seeing a trend in sqlite related errors.

## Conditions of satisfaction
 - [x] Add better debugging/error handling for all those issues, so it's easier to fix in the future
 - [x] The disk_list class (and sub-classes) should take an optional parameter with the table prefix, so we end up with `disk_list_<prefix>_<random>`. Using unique prefixes will help me pinpoint the location of errors such as #5107 

The following bugs are fixed:
 - [ ] DBException: database disk image is malformed #4905 
    * SYNC=On, experiment to see of this bugs dissapears https://github.com/andresriancho/w3af/commit/db0b758d4112b5daadf4422dee11a6096b0d17d8
    * The commit was not present in 1.6.0.5 (latest Kali) but will be present in 1.6.46

 - [ ] DBException: no such table: disk_list_sjbgeWjyPPFpESyFtvggcuDtgzwyfw #5107
    * Added name/prefix to all tables to detect if there is a pattern

## Ideas
 * Remember thread in sqlite-users I started

 * Regarding sync=OFF

> I strongly recommend not playing with fire.

It might be a good idea to disable it for a month to see if the sqlite related errors go away.

 * Sqlite has temporary tables? They've mentioned this in the mailing list thread when I said that I removed the tables after using them:

> It sounds like what you could use temporary tables and let SQLite do the work for you.
> But please note: Temporary tables *always* operate as if synchronous=off, regardless of the actually synchronous setting....

 * Try with https://github.com/rogerbinns/apsw
