### ISSUE TITLE
DBException: database or disk is full - Should stop the scan

### ISSUE THREAD

**Issue by 1d3df9903ad** [andresriancho/w3af#5343]
## Goals
 - [x] The scan should stop without crashing
 - [x] A message should be shown to the user explaining that he has no disk space left

## Tasks
 - [x] Add a global free disk space check that's triggered when there is 50mb of disk space left on the partition where the HTTP cache and DB is saved. Note that I said "global", this means that it's not tied to the DBMS.
 - [x] The check should run once every N requests
 - [x] When it fails it should raise a IOError and end up in `w3afCore.py` error handling for no disk space left:
```python
        except IOError as (error_id, error_msg):
            # https://github.com/andresriancho/w3af/issues/9653
            # IOError: [Errno 28] No space left on device
            if error_id == errno.ENOSPC:
                msg = ('The w3af scan will stop because the file system'
                       ' is running low on free space. Check the "%s" directory'
                       ' size, overall disk usage and start the scan again.')
                msg %= get_home_dir()

                print(msg)
                om.out.error(msg)
            else:
                raise
```
 - [x] Verify that the fix prevents the current issue (note that it's on the GUI!)

## Version Information
```
  Python version: 2.7.3 (default, Mar 14 2014, 17:55:54) [GCC 4.6.3]
  GTK version: 2.24.10
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.0.5
    Revision: 880379b54b - 26 Sep 2014 18:32
    Branch: master
    Local changes: No
    Author: Andres Riancho and the w3af team.
```
## Traceback
```pytb
Traceback (most recent call last):
  File "/home/user/w3af/w3af/core/ui/gui/tabs/log/graph.py", line 88, in draw_handler
    reset = self._redraw_gen.next()
  File "/home/user/w3af/w3af/core/ui/gui/tabs/log/graph.py", line 119, in _redraw_all
    if len(self.all_messages) < 2:
  File "/home/user/w3af/w3af/core/data/db/disk_list.py", line 247, in __len__
    r = self.db.select_one(query)
  File "/home/user/w3af/w3af/core/data/db/dbms.py", line 51, in inner_verify_started
    return meth(self, *args, **kwds)
  File "/home/user/w3af/w3af/core/data/db/dbms.py", line 119, in select_one
    return self.select(query, parameters)[0]
  File "/home/user/w3af/w3af/core/data/db/dbms.py", line 51, in inner_verify_started
    return meth(self, *args, **kwds)
  File "/home/user/w3af/w3af/core/data/db/dbms.py", line 110, in select
    return future.result()
  File "/usr/lib/pymodules/python2.7/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/lib/pymodules/python2.7/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
DBException: database or disk is full

```
