### ISSUE TITLE
Authentication plugin: username_field contains [] - No credentials sent

### ISSUE THREAD

**Issue by Reality-Labs** [andresriancho/w3af#5593]
When using the detailed auth plugin I get this error:
Can't login into web application as uername/password

although I am 100% sure that it is right because I logged in using a browser and it logged in 

and I think it is because of the "username_field" and "password_field" because mine is set to "data[User][username]" and "data[User][password]" and I think that those brackets are the problem

System Info.:
 Python version: 2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]
 GTK version: 2.24.10
 PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.0.5

**Comment by andresriancho** [comment]
## TODO
 - [ ] Create a test script for authentication plugins in django-moth that has a form with user parameter named `foo[user]`
 - [ ] Analyze traffic with wireshark while submitting the form with Chrome and Firefox
 - [ ] Analyze traffic with wireshark while submitting the form with w3af
 - [ ] Make w3af behave like Chrome/Firefox
 - [ ] Add a unittest for the `auth.detailed` plugin to make sure it works against the test script coded in the first step

**Comment by andresriancho** [comment]
Chrome:
![screenshot from 2015-04-22 15 49 06](https://cloud.githubusercontent.com/assets/865200/7282566/2bdfa726-e907-11e4-9493-1a276d131878.png)

Firefox:
![screenshot from 2015-04-22 15 50 36](https://cloud.githubusercontent.com/assets/865200/7282591/59f1bc58-e907-11e4-88ae-9771d286f31f.png)

Both agree in sending the square brackets URL encoded

**Comment by andresriancho** [comment]
w3af isn't encoding the first POST request, but it is doing it for the following:

![screenshot from 2015-04-22 15 59 59](https://cloud.githubusercontent.com/assets/865200/7282788/b17ad9cc-e908-11e4-9527-29b924e4d224.png)

![screenshot from 2015-04-22 16 00 37](https://cloud.githubusercontent.com/assets/865200/7282791/be573078-e908-11e4-8ac8-f8626e575762.png)

**Comment by Reality-Labs** [comment]
Wow it took you 6 months……………sorry but that's awful (shit) support

**Comment by andresriancho** [comment]
hahaha, you think this is microsoft or apple? "awful support" ? You get to complain when:
 * You pay for something
 * You contribute to a project and the project lead doesn't merge your changes

In any other case, you need to be thankful that a software is open source / free.

Welcome to the real world.
