### ISSUE TITLE
Find other lxml parsers like phishtank - Identify memory leaks

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#8614]
## History
I fixed a huge memory leak in the phishtank plugin by removing the lxml parser, are there other plugins which use it to parse large XML files? Do they leak memory too? Should I remove them?

```console
[pablo:/home/pablo/pch/w3af] [w3af] develop(2) ± find . -type f -name '*.py' | xargs grep -n -i "etree.fromstring"
./w3af/core/data/parsers/sgml.py:169:            etree.fromstring(resp_body, parser)
./w3af/core/data/parsers/sgml.py:180:            etree.fromstring(resp_body, parser)
./w3af/core/data/parsers/sgml.py:206:                self._dom = etree.fromstring(resp_body, parser)
./w3af/core/data/parsers/sgml.py:216:                self._dom = etree.fromstring(resp_body, parser)
./w3af/plugins/crawl/import_results.py:158:            requests = etree.fromstring(file(burp_file).read(), parser)
./w3af/plugins/tests/output/test_xml_file.py:86:        vulns = etree.fromstring(file(self.FILENAME).read(), parser)
[pablo:/home/pablo/pch/w3af] [w3af] develop(2) ±
```

Seems that I need to focus on `sgml.py` and it's sub-classes:
 * HTMLParser
 * WMLParser

## Problem
In the subprocess created by ParserCache we load all the HTML in memory, can we migrate to https://www.ibm.com/developerworks/library/x-hiperfparse/ ? Something I suspect is that the HTMLParser will load all the HTML in memory if we use recover flag?

## TODO

The way we're doing it now is by loading all the HTML in memory, but measuring memory usage is really difficult because it's "one line of code" (`etree.fromstring(resp_body, parser)`) and it's difficult to measure what's the peak memory usage in that line, I can measure memory usage before and after but not during (C lib). The only way I know how to do it is by using an extremely large XML document (like the one from phishtank). So, my goals are:

 - [x] Create a huge HTML document
 - [x] Create a test that parses the huge HTML doc
 - [x] Measure memory usage in a different terminal using htop: 262 MB is the peak memory used when parsing the document using `etree.fromstring(resp_body, parser)`
 - [x] Modify the parser to use iterparse
 - [x] Measure memory usage in a different terminal using htop:
  - [x] 106MB before making sure all tests were PASS
  - [x] 231MB after making sure all tests PASS

The 231MB result makes me believe that I'm doing something wrong with the parser code in python.

If the second measurement uses less memory then we win :+1: 

Command to reproduce tests:
```
python -m memory_profiler w3af/core/data/parsers/tests/test_htmlparser_performance.py
```
## Related with
 * This improvement to the phishtank plugin https://github.com/andresriancho/w3af/commit/59c33ae9a69addec9055df9166ef2b16f6caa4c0#diff-be6fb58302c6bd517f3c2fc88a0c396a
 * MemoryError Kali (with 1.9G free RAM) scanning DVWA - 1.6.0.5 Kali package #8502
 * High memory usage with new forking parser cache #7503
 * Memory improvement for HTML parsing in subprocess #9989

## External references
http://svn.colorstudy.com/home/ianb/python-html-perf/results.html
http://www.ianbicking.org/blog/2008/03/python-html-parser-performance.html

**Comment by andresriancho** [comment]
## TODO
 - [ ] `def data(self, data):` in html.py is not called anymore
 - [ ] Error handling in parse will always fail:
```python
            resp_body = resp_body.encode(http_resp.charset,
                                         'xmlcharrefreplace')
```

**Comment by andresriancho** [comment]
Next fix for this at https://github.com/andresriancho/w3af/issues/9990
