### ISSUE TITLE
Improve signatures to detect backdoors

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#8992]
## History
I refactored the find_backdoors plugin in order to use specific signatures, which might get outdated.

## Task
 - [ ] Find new signatures to detect web shells and backdoors
 - [ ] Update the signatures file using the shells at https://github.com/tennc/webshell
 - [ ] Update the signatures file using https://github.com/Neo23x0/Loki/blob/master/signatures/thor-webshells.yar , note that some signatures match source code and we don't have access to it, just to the rendered response
 - [ ] Create a task just like this one so I remember to keep doing this periodically

**Comment by preetpdsilva-netizen** [comment]
hey @andresriancho  i would like to help you in this issue can you assign to me .
