### ISSUE TITLE
Use vulndb's python-sdk to provide long descriptions in w3af

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#9174]
## Tasks
 - [x] Add the features in Info and Vuln inside w3af's core
 - [x] Write a unittest that will extract all vulnerability names from the source and verify they are in vulns.py , the tests don't cover 100% of the code/vulns
 - [x] Create a dict that translates vuln names to vulndb_id , and use that information when creating Info instances. Allow the dev to override the translation by specifying a vulndb_id in `__init__`
 - [x] Add the features to handle long descriptions to the following output plugins:
  - [x] html_file
  - [x] xml_file
 - [x] In the xml_file plugin modifications make sure to:
  - [x] Bump the XML version and update the XSD
  - [x] Let people know via mailing list and twitter that XML output will soon change in master
 - [x] Show the long descriptions in the GUI
 - [x] Change the README.md in vulndb/data to explain that w3af already includes it
 - [x] Add support for references in:
   - [x] GUI
   - [x] html
   - [x] xml
 - [x] Add `python-webkit` dependency to:
  - [x] Kali package
  - [x] All platforms in dependency_check module

## Vulnerability database required improvements
There are a lot of vulnerabilities in `vulns.py` which don't have a reference to the vulndb/data:
 - [x] Split them in two groups: MUST-HAVE, NICE-TO-HAVE
 - [x] Create a ticket with the must haves in vulndb/data
 - [x] Create a ticket with the nice to haves in vulndb/data
 - [x] Write the JSON for the must haves
 - [x] Update python-sdk
 - [x] Update requirements.py in w3af
 - [x] Update vulns.py in w3af to point to the new db entries

## Feature branch
https://github.com/andresriancho/w3af/tree/feature/longdesc

## Related
 * WASC / OWASP References for all vulnerabilities #53
 * https://github.com/vulndb/python-sdk
