### ISSUE TITLE
New plugin: Content type incorrectly stated

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#9351]
## Context
I've seen this in some burp reports:

>Summary
The response contains the following Content-type statement:
`Content-Type: text/html; charset=utf-8`

> The response states that it contains HTML. However, it actually appears to contain JSON.

> Issue background
If a web response specifies an incorrect content type, then browsers may process the response in unexpected ways. If the specified content type is a renderable text-based format, then the browser will usually attempt to parse and render the response in that format. If the specified type is an image format, then the browser will usually detect the anomaly and will analyze the actual content and attempt to determine its MIME type. Either case can lead to unexpected results, and if the content contains any user-controllable data may lead to cross-site scripting or other client-side vulnerabilities.  In most cases, the presence of an incorrect content type statement does not constitute a security flaw, particularly if the response contains static content. You should review the contents of the response and the context in which it appears to determine whether any vulnerability exists.  

> Issue remediation
For every response containing a message body, the application should include a single Content-type header which correctly and unambiguously states the MIME type of the content in the response body.  

## Tasks
 - [ ] Create a new plugin that will detect this vulnerability
 - [ ] Create unittests
 - [ ] Add the vulnerability to vulndb/data
 - [ ] Create a new python-sdk release for the new vulndb/data
 - [ ] Update requirements.py to point to the new python-sdk release
 - [ ] Link vulns.py to the new vulnerability ID from vulndb/data

## Algorithm
TBD
