### ISSUE TITLE
Support fuzzing Flash AMF using PyAMF

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#9357]
## Use case
As a user that owns a complex Flash application I want to be able to identify vulnerabilities in the AMF "endpoints" exposed server-side in order to reduce my risk.

## Task
 - [ ] Research the types supported by AMF, to identify which parts I could fuzz
 - [ ] Create an amf_container, similar to the [json_container](https://github.com/andresriancho/w3af/tree/master/w3af/core/data/dc) using pyamf
 - [ ] Create an json_mutant, similar to the [json_mutant](https://github.com/andresriancho/w3af/tree/master/w3af/core/data/fuzzer/mutants)
 - [ ] Unittest the fuzzer by creating an AMF endpoint for django-moth (using pyamf) and identifying vulnerabilities in that
 - [ ] Remember to add the new dependency (pyamf) in requirements.py

## Priority
This feature is not a must-have, but really interesting for new contributor that wants to understand w3af's core.

## Limitations
Since w3af doesn't (and at the moment there is not even a plan) have a browser which will "click" inside the flash / decompile it, the AMF traffic to be fuzzed would have to be generated manually by the user.

## References
There is a great library for AMF in python https://github.com/hydralabs/pyamf , with great coverage and support.
