### ISSUE TITLE
New plugin CVE-2015-1635 - RCE in Windows HTTP.sys

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#9479]
## Warning
The current detection technique seems to kill the OS. We don't want that. Wait until someone identifies a better way to identify the vulnerability.

## Tasks
 - [ ] Understand the following resources:
  - [ ] http://pastebin.com/ypURDPc4
  - [ ] https://www.cloudshark.org/captures/0132eb74ecd3
  - [ ] https://technet.microsoft.com/library/security/ms15-034
  - [ ] https://github.com/rapid7/metasploit-framework/pull/5150 see if someone is worried about DoS
> This won't cause a BSOD, try Range: bytes=18-18446744073709551615 instead

  - [ ] https://ma.ttias.be/remote-code-execution-via-http-request-in-iis-on-windows/?hn : "When sending such a request, it can trigger a blue screen on the Windows Server, effectively rendering it offline." We don't want to do that!
  - [ ] https://github.com/pr4jwal/quick-scripts/blob/master/ms15-034.nse
 - [ ] Assess the risks of sending that request:
   - [ ] Will it DoS a vulnerable IIS server?
   - [ ] Will it DoS a patched IIS server?
   - [ ] Will it DoS an Apache/Nginx?
 - [ ] Migrate the check to a w3af audit plugin (make sure you use the w3af way to send HTTP requests, do not use socket)
 - [ ] Create a unittest similar to [this one](https://github.com/andresriancho/w3af/blob/master/w3af/plugins/tests/audit/test_shell_shock.py) to make sure the plugin works
