### ISSUE TITLE
max_discovery_time is ignored?

### ISSUE THREAD

**Issue by kyprizel** [andresriancho/w3af#9636]
Spider starts crawling and never stops.

example config:
```
[misc-settings]
fuzzCookie = False
fuzz_url_filenames = False
fuzz_url_parts = False
fuzz_cookies = False
max_discovery_time = 1
maxThreads = 0
autoDependencies = True
form_fuzzing_mode = t

[crawl.web_spider]
only_forward = False
follow_regex = .*
ignore_regex = .*captcha.*

[target]
target = http://moscow.auto.ru

[output.console]
verbose = True

**Comment by andresriancho** [comment]
Tagged as `core` since this is handled at core level and doesn't have anything to do with the web_spider

**Comment by andresriancho** [comment]
Need some manual to verify, there is a unittest for this feature but it seems to be failing/disabled.
https://github.com/andresriancho/w3af/blob/b7cffaa62ab12b3077870837c44cf23043beb9ed/w3af/core/controllers/core_helpers/consumers/tests/test_crawl_infrastructure.py#L33

**Comment by andresriancho** [comment]
## TODO
 - [ ] Manually reproduce and confirm bug reported by @kyprizel 
 - [ ] Fix [the unittest](https://github.com/andresriancho/w3af/blob/b7cffaa62ab12b3077870837c44cf23043beb9ed/w3af/core/controllers/core_helpers/consumers/tests/test_crawl_infrastructure.py#L33) or code a new one to test the feature
 - [ ] Try to reproduce the issue in a test
 - [ ] Fix the issue

**Comment by kyprizel** [comment]
This code breaks some stuff
https://github.com/andresriancho/w3af/commit/8ff0e0956203d90a2bceca98b6f8152216464e2e#diff-e6a2b2a806fec7bf75fb3e69e7e5b14d

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/w3af/core/controllers/threads/pool276.py", line 134, in worker
    wrapped = create_detailed_pickling_error(e, result[1])
  File "/usr/lib/python2.7/site-packages/w3af/core/controllers/threads/pool276.py", line 150, in create_detailed_pickling_error
    for k, v in instance.__dict__.iteritems():
AttributeError: 'tuple' object has no attribute '__dict__'

also there can be another problem with Python 2.7.3
http://bugs.python.org/issue14881

**Comment by andresriancho** [comment]
@kyprizel thanks for reporting the but in `create_detailed_pickling_error`, I've just fixed it in the develop branch. It should take much time for that fix to make it to master.

Please note that at this moment `develop` is a little bit broken, so using it might be unstable.

**Comment by andresriancho** [comment]
Regarding both bugs you reported in the comment:
 * `create_detailed_pickling_error`
 * http://bugs.python.org/issue14881

Do you have a good way I can reproduce them both? If so, please create two new issues. Thanks!

**Comment by andresriancho** [comment]
@kyprizel ping on the last comment

**Comment by andresriancho** [comment]
Going to be working on the main issue, bugs reported in the comment will be ignored unless @kyprizel adds more details.

**Comment by kyprizel** [comment]
Version from master hangs with

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/w3af-console/lib/python2.7/site-packages/w3af/core/controllers/threads/pool276.py", line 438, in _handle_results
    task = get()
TypeError: ('__init__() takes exactly 4 arguments (3 given)', <class 'w3af.core.controllers.threads.pool276.DetailedMaybeEncodingError'>, ('PicklingError("Can\'t pickle <type \'dictproxy\'>: attribute lookup __builtin__.dictproxy failed",)', '<HTMLParser DocumentParser for "<HTTPResponse | 200 | https://xxxx/ | id:34 | fcache:True>">'))


I've switched to dev version and it works ok.

**Comment by andresriancho** [comment]
Are you able to reproduce that dictproxy problem each time you run w3af? Could you create a different issue explaining how?

**Comment by kyprizel** [comment]
Sorry, I've swtiched to devel version already and can't reproduce a problem there any more :(

**Comment by andresriancho** [comment]
Ok, this had nothing to do with the max discovery time, it was an issue with the profile which was "invalid" , w3af failed to load it as expected and silently failed. Now if you try the same you'll get:

```text
./w3af_console -p 9636.pw3af 
w3af>>> profiles use 9636.pw3af /home/pablo/pch/w3af
The profile you are trying to load (9636.pw3af) seems to be outdated, this is a common issue which happens when the framework is updated and one of its plugins adds/removes one of the configuration parameters referenced by a profile, or the plugin is removed all together.

The profile was loaded but some of your settings might have been lost. This is the list of issues that were found:

    - Setting the framework misc-settings raised an exception due to unknown or invalid configuration parameters. The OptionList doesn't contain an option with thename: "fuzzCookie"

We recommend you review the specific plugin configurations, apply the required changes and save the profile in order to update it and avoid this message. If this warning does not disappear you can manually edit the profile file to fix it.
The plugins configured by the scan profile have been enabled, and their options configured.
Please set the target URL(s) and start the scan.
w3af>>> 

```

**Comment by andresriancho** [comment]
Waiting for the tests to finish before closing
