### ISSUE TITLE
Search engine code expects xurllib to follow redirects

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#9966]
The code at `search_engines/google.py` which I print below expects that the xurllib follows the redirect which is returned by Google:

```python
    def _do_GET(self, url, with_rand_ua=True):
        if not isinstance(url, URL):
            msg = 'The url parameter of a _do_GET must be of url.URL type.'
            raise ValueError(msg)

        if with_rand_ua:
            random_ua = get_random_user_agent()
            headers = Headers([('User-Agent', random_ua)])
        else:
            # Please note that some tests show that this is useful for the
            # mobile search.
            headers = Headers([('User-Agent', '')])

        return self._uri_opener.GET(url, headers=headers)
```

This is a regression which I introduced a while ago and didn't notice. The change which I did a while ago was "do not follow redirects", which was done at `redirect.py`

This means that google and potentially bing search engines won't work.

## Tasks
 - [x] Enable a simple unittest for google search engine, make sure it fails because of this
 - [x] Change the xurllib to have a `follow_redirects` flag. The default should be `False`
 - [x] When following redirects make sure we don't end up in a loop
 - [x] Make the `follow_redirect` available via `GET` and `HEAD`. Note that `POST` shouldn't have one
 - [x] Unittest redirects in xurllib
    - [x] Redirects with 302 and 301 are followed
    - [x] The log stores all the HTTP requests as expected
    - [x] IDs are assigned to each request
    - [x] Redirect loops are avoided
    - [x] A response with a 302 code that doesn't have a 'location' header
    - [x] A redirect location to file://
 - [x] Make sure the test we enabled in the first step passes now

**Comment by andresriancho** [comment]
An historic commit where this worked:
https://github.com/andresriancho/w3af/commit/64ac4b32

**Comment by andresriancho** [comment]
Failing test is w3af/core/data/search_engines/tests/test_google.py:TestGStandardSearch
