### ISSUE TITLE
get_dom performance and timeout improvements

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#9990]
## Problems
 * `get_dom` is called only from the main process (from different threads). So the HTML is parsed in the main process without any timeout (which we impose for the subprocesses in parser_cache). This makes the timeout feature almost useless, since it only works when w3af doesn't call `get_dom`

 * When we call `get_dom` we load all the HTML in memory and keep it there until the HTTPResponse is unreferenced and cleaned by the gc.

## Solutions
 * Can we replace XPATH with a different thing which operates in "sax mode"? This would avoid storing the dom in memory but would force me to parse the same response once for each "XPATH query"

 * Move all the `get_dom` code which is run in the `MainThread` to a subprocess

### `get_tags_by_filter` development
`get_tags_by_filter` requirements:
 - [x] Receives two parameters
   * tags: Tuple with the names of the tags (as strings) we want to get from the HTTP response body
   * http_response: The HTTP response
 - [x] Implementation uses etree.iterparse for going through the HTML. The `tags` parameter is passed to the iterparse kwargs which will guarantee lightning fast parsing, which frees me from caches
 - [x] `get_tags_by_filter` replaces `get_dom` in sgml.py
 - [x] `get_tags_by_filter` yields result tuples with `(tag_name, tag_attrs, tag_text)`
 - [x] Find a good way to expose this to developers, maybe make it part of ParserCache so we can use the same subprocess pool? That might confuse users because I'm not caching these results?
 - [x] Write unittests for initial implementation without multiprocessing
 - [x] Should run in a different process
 - [x] Yields using a multiprocessing Queue
 - [x] Has a timeout just like the parser
 - [x] Write unittests for all features working in subprocesses

## Implementation in plugins
 - [x] The plugins which now use `etree.XPath` should use the new feature:
```console
$ find . -name '*.py' | xargs grep 'etree.XPath'
./w3af/plugins/grep/websockets_links.py:            script_tag_xpath = etree.XPath(SCRIPT_TAG_XPATH)
./w3af/plugins/grep/form_autocomplete.py:        self._autocomplete_forms_xpath = etree.XPath(AUTOCOMPLETE_FORMS_XPATH)
./w3af/plugins/grep/form_autocomplete.py:        self._pwd_input_xpath = etree.XPath(PWD_INPUT_XPATH)
./w3af/plugins/grep/form_autocomplete.py:        self._text_input_xpath = etree.XPath(TEXT_INPUT_XPATH)
./w3af/plugins/grep/feeds.py:        self._tag_xpath = etree.XPath('//rss | //feed | //opml')
./w3af/plugins/grep/file_upload.py:        self._file_input_xpath = etree.XPath(FILE_INPUT_XPATH)
./w3af/plugins/grep/cross_domain_js.py:        self._script_src_xpath = etree.XPath(SCRIPT_SRC_XPATH)
./w3af/plugins/grep/objects.py:        self._tag_xpath = etree.XPath('//object | //applet')
./w3af/plugins/audit/phishing_vector.py:        self._tag_xpath = etree.XPath('//iframe | //frame')
$
```
 - [x] Remove the `HTTPResponse.get_dom()`

Plugins to change:
 - [x] ./w3af/plugins/grep/cross_domain_js.py
 - [x] ./w3af/plugins/grep/feeds.py
 - [x] ./w3af/plugins/grep/file_upload.py
 - [x] ./w3af/plugins/grep/form_autocomplete.py
 - [x] ./w3af/plugins/grep/objects.py
 - [x] ./w3af/plugins/grep/websockets_links.py
 - [x] ./w3af/plugins/grep/password_profiling_plugins/html.py
 - [x] ./w3af/plugins/grep/path_disclosure.py
 - [x] ./w3af/plugins/grep/symfony.py
 - [x] ./w3af/plugins/tests/grep/test_symfony.py

**Comment by andresriancho** [comment]
This could be important!

```
Filename: w3af/core/data/parsers/tests/test_htmlparser_performance.py

Line #    Mem usage    Increment   Line Contents
================================================
    96     20.2 MiB      0.0 MiB   @profile
    97                             def test():
    98                                 """
    99                                 Run using:
   100                                     python -m memory_profiler w3af/core/data/parsers/tests/test_htmlparser_performance.py
   101                             
   102                                 That will activate the profiler.
   103                                 """
   104     22.6 MiB      2.3 MiB       body = file(OUTPUT_FILE).read()
   105     22.6 MiB      0.0 MiB       url = URL('http://www.clarin.com.ar/')
   106     22.6 MiB      0.0 MiB       headers = Headers()
   107     22.6 MiB      0.0 MiB       headers['content-type'] = 'text/html'
   108     22.6 MiB      0.0 MiB       response = HTTPResponse(200, body, headers, url, url, charset='utf-8')
   109                             
   110     90.4 MiB     67.8 MiB       p = HTMLParser(response)
   111     88.4 MiB     -2.0 MiB       del p
   112                             
   113     94.8 MiB      6.4 MiB       p = HTMLParser(response)
   114     94.0 MiB     -0.8 MiB       del p
   115                             
   116     98.7 MiB      4.6 MiB       p = HTMLParser(response)
   117     98.7 MiB      0.0 MiB       del p
   118                             
   119    102.6 MiB      3.9 MiB       p = HTMLParser(response)
   120    102.6 MiB      0.0 MiB       del p
   121                             
   122    106.5 MiB      3.9 MiB       p = HTMLParser(response)
   123    106.5 MiB      0.0 MiB       del p
   124                             
   125    110.3 MiB      3.9 MiB       p = HTMLParser(response)
   126    110.3 MiB      0.0 MiB       del p
   127                             
   128    114.2 MiB      3.9 MiB       p = HTMLParser(response)
   129    114.2 MiB      0.0 MiB       del p
   130                             
   131    118.1 MiB      3.9 MiB       p = HTMLParser(response)
   132    118.1 MiB      0.0 MiB       del p
```

Note how each time we run the HTMLParser 3.9mb are allocated and never returned to the OS. If this happens with `get_dom` then we've found a huge memory leak!

**Comment by andresriancho** [comment]
## TODO
 - [ ] Move `get_tags_by_filter` to sgml.py , and remove the "implicit call to `_parse`" in `__init__` to make sure that we don't parse when we just want to `get_tags_by_filter`

**Comment by andresriancho** [comment]
## Pre-merge TODO
 - [ ] Analyze memory usage performance:
   - [ ] 7f80cea4b7d4b307fb59f2bae01d78941f57e007
     - [ ] Run 1 memory usage:
     - [ ] Run 2 memory usage:
   - [ ] e32e529236f9685d624a943e6a2d88e5a9bf1c4e
     - [ ] Run 1 memory usage:
     - [ ] Run 2 memory usage:

## Collector configuration
 - [ ] Disable pytracemalloc
 - [ ] Run for 45 minutes
 - [ ] Make sure we don't hit the 60 second parser timeout

**Comment by andresriancho** [comment]
* **Pre-merge TODO** shows that there are no regressions when `grep path_disclosure`
 * **Pre-merge TODO** shows that there are XX(memory usage improvements) when `grep all`
